// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MindSyn",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MindSyn",
            targets: ["AppModule"],
            bundleIdentifier: "com.weaae.MindSyn",
            teamIdentifier: "346D566F8S",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .smiley),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "MindSyn needs microphone access to capture your voice and create tasks."),
                .speechRecognition(purposeString: "MindSyn uses speech recognition to convert your voice into text tasks.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
